title: Elisa Legnani
description: 
baseurl: "/new_website"
url: "https://elisalegnani.github.io/new_website/"

email: elegnani97@gmail.com
github_username:  ElisaLegnani

theme: minima
plugins:
  - jekyll-target-blank

exclude: [vendor]