title: Elisa Legnani
description: 
baseurl: "/new_website"
url: "https://elisalegnani.github.io/new_website/"
image_path: /new_website/assets/images

contact:
  - title: Email
    url: mailto:elegnani97@gmail.com
    icon: envelope
  - title: GitHub
    url: https://github.com/ElisaLenani
    icon: github
  - title: LinkedIn
    url: https://www.linkedin.com/in/elisa-legnani-32590819b/
    icon: linkedin
  
plugins:
  - jekyll-target-blank

exclude: [vendor]